import { useEffect, useRef, useState } from "react";
import {
  ThumbsUp,
  ThumbsDown,
  Copy,
  Volume2,
  Square,
  RefreshCw,
  Share2,
  FileDown,
  Star,
  MoreHorizontal,
  Check,
  Languages,
  PenLine,
  Sparkles,
  ListTree,
  Flag,
  FileText,
  Code2,
} from "lucide-react";

type Props = {
  text: string;
  onRegenerate?: () => void;
  onFollowUp?: (prompt: string) => void;
};

const KEY_SAVED = "farmx-ai:saved";
const KEY_VOTES = "farmx-ai:votes";

function readMap(key: string): Record<string, string> {
  if (typeof window === "undefined") return {};
  try {
    return JSON.parse(localStorage.getItem(key) || "{}") as Record<string, string>;
  } catch {
    return {};
  }
}
function writeMap(key: string, map: Record<string, string>) {
  localStorage.setItem(key, JSON.stringify(map));
}

function stripMarkdown(md: string) {
  return md
    .replace(/```[\s\S]*?```/g, (b) => b.replace(/```\w*\n?/g, ""))
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`([^`]*)`/g, "$1")
    .replace(/^\s*[-*]\s+/gm, "• ")
    .replace(/\[(.*?)\]\((.*?)\)/g, "$1")
    .trim();
}

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function MessageActions({ text, onRegenerate, onFollowUp }: Props) {
  const id = useRef(hash(text.slice(0, 200))).current;
  const [vote, setVote] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState<string | null>(null);
  const [speaking, setSpeaking] = useState(false);
  const [more, setMore] = useState(false);

  useEffect(() => {
    setVote(readMap(KEY_VOTES)[id] ?? null);
    setSaved(Boolean(readMap(KEY_SAVED)[id]));
  }, [id]);

  useEffect(
    () => () => {
      if (typeof window !== "undefined") window.speechSynthesis?.cancel();
    },
    [],
  );

  const flash = (label: string) => {
    setCopied(label);
    setTimeout(() => setCopied(null), 1400);
  };

  const copy = async (value: string, label: string) => {
    try {
      await navigator.clipboard.writeText(value);
      flash(label);
    } catch {
      flash("Copy failed");
    }
  };

  const setVoteValue = (v: "up" | "down") => {
    const map = readMap(KEY_VOTES);
    const next = map[id] === v ? null : v;
    if (next) map[id] = next;
    else delete map[id];
    writeMap(KEY_VOTES, map);
    setVote(next);
  };

  const toggleSave = () => {
    const map = readMap(KEY_SAVED);
    if (map[id]) delete map[id];
    else map[id] = text.slice(0, 4000);
    writeMap(KEY_SAVED, map);
    setSaved(Boolean(map[id]));
  };

  const readAloud = () => {
    const synth = window.speechSynthesis;
    if (!synth) return flash("Not supported");
    if (speaking) {
      synth.cancel();
      setSpeaking(false);
      return;
    }
    const u = new SpeechSynthesisUtterance(stripMarkdown(text).slice(0, 4000));
    u.onend = () => setSpeaking(false);
    u.onerror = () => setSpeaking(false);
    synth.cancel();
    synth.speak(u);
    setSpeaking(true);
  };

  const share = async () => {
    const plain = stripMarkdown(text);
    if (navigator.share) {
      try {
        await navigator.share({ title: "FarmX AI", text: plain });
        return;
      } catch {
        /* cancelled */
      }
    }
    void copy(plain, "Copied to share");
  };

  const exportPdf = () => {
    const w = window.open("", "_blank", "width=800,height=900");
    if (!w) return flash("Allow pop-ups");
    w.document
      .write(`<!doctype html><html><head><meta charset="utf-8"><title>FarmX AI Report</title>
      <style>body{font-family:ui-sans-serif,system-ui,Arial;margin:32px;line-height:1.6;color:#111}
      h1{font-size:18px;border-bottom:1px solid #ddd;padding-bottom:8px}
      pre{white-space:pre-wrap;word-wrap:break-word;font-family:inherit;font-size:14px}
      footer{margin-top:32px;font-size:11px;color:#666}</style></head>
      <body><h1>FarmX AI</h1><pre>${escapeHtml(stripMarkdown(text))}</pre>
      <footer>Generated by FarmX AI — SYLUTION LTD</footer></body></html>`);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 350);
  };

  const exportDocx = () => {
    const html = `<html xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"></head>
      <body><h1>FarmX AI</h1><pre style="white-space:pre-wrap;font-family:Calibri,sans-serif">${escapeHtml(stripMarkdown(text))}</pre></body></html>`;
    download("farmx-ai-response.doc", html, "application/msword");
    flash("Exported");
  };

  const followUp = (prompt: string) => {
    setMore(false);
    onFollowUp?.(prompt);
  };

  return (
    <div className="relative mt-2">
      <div className="flex flex-wrap items-center gap-0.5">
        <Act label="Good response" active={vote === "up"} onClick={() => setVoteValue("up")}>
          <ThumbsUp size={15} />
        </Act>
        <Act label="Bad response" active={vote === "down"} onClick={() => setVoteValue("down")}>
          <ThumbsDown size={15} />
        </Act>
        <Act label="Copy" onClick={() => void copy(text, "Copied")}>
          <Copy size={15} />
        </Act>
        <Act label="Read aloud" active={speaking} onClick={readAloud}>
          {speaking ? <Square size={14} /> : <Volume2 size={15} />}
        </Act>
        {onRegenerate && (
          <Act label="Regenerate" onClick={onRegenerate}>
            <RefreshCw size={15} />
          </Act>
        )}
        <Act label="Share" onClick={() => void share()}>
          <Share2 size={15} />
        </Act>
        <Act label="Export PDF" onClick={exportPdf}>
          <FileDown size={15} />
        </Act>
        <Act label="Save" active={saved} onClick={toggleSave}>
          <Star size={15} fill={saved ? "currentColor" : "none"} />
        </Act>
        <Act label="More" active={more} onClick={() => setMore((m) => !m)}>
          <MoreHorizontal size={15} />
        </Act>
        {copied && (
          <span className="ml-1 inline-flex items-center gap-1 text-[11px] text-muted-foreground">
            <Check size={12} />
            {copied}
          </span>
        )}
      </div>

      {more && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setMore(false)} />
          <div
            className="absolute left-0 z-50 mt-1 w-56 animate-fade-in overflow-hidden rounded-2xl border border-border shadow-xl"
            style={{ background: "var(--surface)" }}
          >
            <MenuItem
              icon={Code2}
              label="Copy Markdown"
              onClick={() => {
                setMore(false);
                void copy(text, "Markdown copied");
              }}
            />
            <MenuItem
              icon={FileText}
              label="Copy Plain Text"
              onClick={() => {
                setMore(false);
                void copy(stripMarkdown(text), "Text copied");
              }}
            />
            <MenuItem
              icon={FileDown}
              label="Export DOCX"
              onClick={() => {
                setMore(false);
                exportDocx();
              }}
            />
            <MenuItem
              icon={Languages}
              label="Translate"
              onClick={() =>
                followUp(
                  "Translate your last answer into Hausa, then English. Keep the same structure.",
                )
              }
            />
            <MenuItem
              icon={PenLine}
              label="Continue Writing"
              onClick={() => followUp("Continue your last answer from exactly where it stopped.")}
            />
            <MenuItem
              icon={Sparkles}
              label="Simplify"
              onClick={() =>
                followUp(
                  "Rewrite your last answer in very simple language a beginner farmer can understand.",
                )
              }
            />
            <MenuItem
              icon={ListTree}
              label="More Detailed"
              onClick={() =>
                followUp(
                  "Give a much more detailed version of your last answer, with practical steps and numbers.",
                )
              }
            />
            <MenuItem
              icon={Flag}
              label="Report Response"
              danger
              onClick={() => {
                setMore(false);
                flash("Reported. Thank you.");
              }}
            />
          </div>
        </>
      )}
    </div>
  );
}

function Act({
  children,
  label,
  onClick,
  active,
}: {
  children: React.ReactNode;
  label: string;
  onClick?: () => void;
  active?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      title={label}
      aria-label={label}
      className="flex h-8 w-8 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-[color:var(--surface-2)] hover:text-foreground active:scale-95"
      style={active ? { background: "var(--surface-2)", color: "var(--foreground)" } : undefined}
    >
      {children}
    </button>
  );
}

function MenuItem({
  icon: Icon,
  label,
  onClick,
  danger,
}: {
  icon: typeof Copy;
  label: string;
  onClick: () => void;
  danger?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      className={`flex w-full items-center gap-3 px-3 py-2.5 text-left text-sm transition-colors hover:bg-[color:var(--surface-2)] ${danger ? "text-destructive" : ""}`}
    >
      <Icon size={15} className={danger ? "" : "text-muted-foreground"} />
      {label}
    </button>
  );
}

function escapeHtml(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function hash(s: string) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return `m${Math.abs(h)}`;
}
