/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiEntitlementRouteImport } from './routes/api/entitlement'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiThreadsRouteImport } from './routes/api/threads'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth.google'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth.logout'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth.reset-password'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth.signup'
import { Route as ApiAuthUpdatePasswordRouteImport } from './routes/api/auth.update-password'
import { Route as ApiPayInitRouteImport } from './routes/api/pay.init'
import { Route as ApiPayVerifyRouteImport } from './routes/api/pay.verify'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiAuthOauthCallbackRouteImport } from './routes/api/auth.oauth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntitlementRoute = ApiEntitlementRouteImport.update({
  id: '/api/entitlement',
  path: '/api/entitlement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadsRoute = ApiThreadsRouteImport.update({
  id: '/api/threads',
  path: '/api/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiAuthUpdatePasswordRoute = ApiAuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => ApiAuthRoute,
} as any)
const ApiPayInitRoute = ApiPayInitRouteImport.update({
  id: '/api/pay/init',
  path: '/api/pay/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayVerifyRoute = ApiPayVerifyRouteImport.update({
  id: '/api/pay/verify',
  path: '/api/pay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthOauthCallbackRoute = ApiAuthOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => ApiAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/chat': typeof ChatRoute
  '/help': typeof HelpRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/entitlement': typeof ApiEntitlementRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/threads': typeof ApiThreadsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/update-password': typeof ApiAuthUpdatePasswordRoute
  '/api/pay/init': typeof ApiPayInitRoute
  '/api/pay/verify': typeof ApiPayVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/auth/oauth/callback': typeof ApiAuthOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/chat': typeof ChatRoute
  '/help': typeof HelpRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/entitlement': typeof ApiEntitlementRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/threads': typeof ApiThreadsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/update-password': typeof ApiAuthUpdatePasswordRoute
  '/api/pay/init': typeof ApiPayInitRoute
  '/api/pay/verify': typeof ApiPayVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/auth/oauth/callback': typeof ApiAuthOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/chat': typeof ChatRoute
  '/help': typeof HelpRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/entitlement': typeof ApiEntitlementRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/threads': typeof ApiThreadsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/update-password': typeof ApiAuthUpdatePasswordRoute
  '/api/pay/init': typeof ApiPayInitRoute
  '/api/pay/verify': typeof ApiPayVerifyRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/auth/oauth/callback': typeof ApiAuthOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/auth-callback'
    | '/chat'
    | '/help'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/terms'
    | '/api/auth'
    | '/api/chat'
    | '/api/entitlement'
    | '/api/generate-image'
    | '/api/threads'
    | '/api/transcribe'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/auth/update-password'
    | '/api/pay/init'
    | '/api/pay/verify'
    | '/api/public/paystack-webhook'
    | '/api/auth/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/auth-callback'
    | '/chat'
    | '/help'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/terms'
    | '/api/auth'
    | '/api/chat'
    | '/api/entitlement'
    | '/api/generate-image'
    | '/api/threads'
    | '/api/transcribe'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/auth/update-password'
    | '/api/pay/init'
    | '/api/pay/verify'
    | '/api/public/paystack-webhook'
    | '/api/auth/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/auth-callback'
    | '/chat'
    | '/help'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/terms'
    | '/api/auth'
    | '/api/chat'
    | '/api/entitlement'
    | '/api/generate-image'
    | '/api/threads'
    | '/api/transcribe'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/reset-password'
    | '/api/auth/signup'
    | '/api/auth/update-password'
    | '/api/pay/init'
    | '/api/pay/verify'
    | '/api/public/paystack-webhook'
    | '/api/auth/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ChatRoute: typeof ChatRoute
  HelpRoute: typeof HelpRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiEntitlementRoute: typeof ApiEntitlementRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiThreadsRoute: typeof ApiThreadsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiPayInitRoute: typeof ApiPayInitRoute
  ApiPayVerifyRoute: typeof ApiPayVerifyRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entitlement': {
      id: '/api/entitlement'
      path: '/api/entitlement'
      fullPath: '/api/entitlement'
      preLoaderRoute: typeof ApiEntitlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads': {
      id: '/api/threads'
      path: '/api/threads'
      fullPath: '/api/threads'
      preLoaderRoute: typeof ApiThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/auth/update-password': {
      id: '/api/auth/update-password'
      path: '/update-password'
      fullPath: '/api/auth/update-password'
      preLoaderRoute: typeof ApiAuthUpdatePasswordRouteImport
      parentRoute: typeof ApiAuthRoute
    }
    '/api/pay/init': {
      id: '/api/pay/init'
      path: '/api/pay/init'
      fullPath: '/api/pay/init'
      preLoaderRoute: typeof ApiPayInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pay/verify': {
      id: '/api/pay/verify'
      path: '/api/pay/verify'
      fullPath: '/api/pay/verify'
      preLoaderRoute: typeof ApiPayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/oauth/callback': {
      id: '/api/auth/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/api/auth/oauth/callback'
      preLoaderRoute: typeof ApiAuthOauthCallbackRouteImport
      parentRoute: typeof ApiAuthRoute
    }
  }
}

interface ApiAuthRouteChildren {
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiAuthUpdatePasswordRoute: typeof ApiAuthUpdatePasswordRoute
  ApiAuthOauthCallbackRoute: typeof ApiAuthOauthCallbackRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiAuthUpdatePasswordRoute: ApiAuthUpdatePasswordRoute,
  ApiAuthOauthCallbackRoute: ApiAuthOauthCallbackRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ChatRoute: ChatRoute,
  HelpRoute: HelpRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiEntitlementRoute: ApiEntitlementRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiThreadsRoute: ApiThreadsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiPayInitRoute: ApiPayInitRoute,
  ApiPayVerifyRoute: ApiPayVerifyRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
